services:
  mysql:
    image: mysql:8.0
    container_name: cars-mysql
    environment:
      MYSQL_DATABASE: cars_db
      MYSQL_USER: cars_user
      MYSQL_PASSWORD: cars_pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./local-data/mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  cars-node:
    build: .
    container_name: cars-node
    ports:
      - "7777:7777"
    environment:
      PORT: 7777
      SERVER_PRIVATE_KEY: "6dcc124be5f382be631d49ba12f61adbce33a5ac14f6ddee12de25272f943f8b"
      SERVER_BASEURL: "http://localhost:7777"
      DATABASE_URL: "mysql://cars_user:cars_pass@mysql:3306/cars_db"
      LOG_LEVEL: "info"
      K3S_TOKEN: "cars-token"
      KUBECONFIG: "/kubeconfig/kubeconfig.yaml"
      DOCKER_HOST: "tcp://dind:2375"
      DOCKER_REGISTRY: "http://cars-registry:5000"
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
      - ./local-data/kubeconfig:/kubeconfig

  k3s-server:
    image: rancher/k3s:latest
    container_name: cars-k3s
    privileged: true
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    command:
      - server
      - "--tls-san=cars-k3s"
      - "--node-name=cars-k3s"
    restart: always
    environment:
      K3S_KUBECONFIG_OUTPUT: /output/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: "666"
      K3S_TOKEN: "cars-token"
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - ./local-data/kubeconfig:/output
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml:ro
    ports:
      - "6443:6443"
      - "8081:80"
      - "8082:443"

  registry:
    image: registry:2
    container_name: cars-registry
    ports:
      - "8083:5000"
    volumes:
      - ./local-data/registry:/var/lib/registry

  dind:
    image: docker:20-dind
    container_name: cars-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: [ "--insecure-registry=cars-registry:5000" ]
    volumes:
      - dind-storage:/var/lib/docker
    ports:
      - "2375:2375"

volumes:
  k3s-server: {}
  dind-storage: {}
